config/routes.rb
Rails.application.routes.draw do
  
  root 'application#angular'

  devise_for :users

  get 'vehicles/upload' => 'data#upload'
  post 'vehicles/import' => 'data#import'

  namespace :api, defaults:{format: :json} do
    namespace :v1 do
      resources :vehicles
      resources :notes, only: [:create, :destroy]
      resources :statuses
      resources :users
    end
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :content, length: { minimum: 2 }

  belongs_to :vehicle
  belongs_to :user

  def self.note_for_status(status)
    user_name = User.find(status.user_id).name
    Note.create(content: "#{user_name} change status to #{status.vehicle_status}", vehicle_id: status.vehicle_id, user_id: status.user_id)
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :user
  belongs_to :vehicle

  def self.update_status_vehicle(vehicle_id, status_params, current_user)
    v = Vehicle.find(vehicle_id)
    prev_status = v.status
    v.build_status(status_params)
    v.status.user = current_user
    prev_status.destroy #this is so I can query a User instance for it's statuses 
                        #and only get active statuses not every status they ever set
    Note.note_for_status(v.status)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  
  enum role: [:guest, :user, :admin]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes
  has_many :notated_vehicles, through: :notes, source: :vehicle

  has_many :statuses
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  validates :VIN, uniqueness: true
  validates :storage, :inclusion => { :in => %w(on-lot off-lot unset) }
  validates :color, :length => { :maximum => 47 }

  before_validation :color_check

  has_attached_file :invoice, default_url: ':style/default_missing_invoice.png'
  validates_attachment_content_type :invoice, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]


  has_many :notes
  has_many :note_authors, through: :notes, source: :user

  has_one :status
  has_one :status_setter, through: :status, source: :user

  def self.import(file, new_or_used)
    CSV.foreach(file.tempfile, headers: true, :header_converters => lambda { |h| h.try(:downcase).tr(" ", "_") }) do |row|
      vehicle_hash = row.to_hash
      vehicle_hash["new_or_used"] = new_or_used
      mappings = {"stock_#" => "stock_no", "colour" => "color", "drivetrain_desc" => "drive_train", "vin" => "VIN"}
      vehicle_hash.keys.each { |k| vehicle_hash[ mappings[k] ] = vehicle_hash.delete(k) if mappings[k] }
      vehicle_hash["photo_url_list"] = vehicle_hash["photo_url_list"].split(",")
      v = Vehicle.create(vehicle_hash.except("dealerid", "dealer_name", "dealer_address", "dealer_city", 
      "dealer_region", "dealer_postal_code", "dealer_phone_number", "description", "placeholder1","placeholder2","series", "third_party_feature_codes", "video_url_duration",
      "video_url", "video_source_", "video_source"))
      v.build_status(user_id: 1, vehicle_status: 'Available')
      v.save
    end
  end

  protected

  def color_check
    if color && color.length > 47
      c = color.delete(' ')
      c.slice! 0..47
    end
  end

end

app/controllers/api/v1/notes_controller.rb
module Api
  module V1
    class NotesController < ApplicationController

      # not sure if i need this index action, but i don't want to delete it in case i get an error.
      # I think rendering groups of notes is handled entirely through the vehicle

      # def index
      #   binding.pry
      #   @notes = Note.where(vehicle_id: (params['vehicle_id'].to_i))
      #   render json: @notes
      # end


      def create
        @note = Note.new(note_params)
        @note.user = current_user
        if @note.save 
          render json: @note
        end 
      end

      def destroy
        respond_with Note.destroy(params[:id]) # not sure about this but it worked, why am i responding?
      end


      private

      def note_params
        params.require(:note).permit(:user_id, :vehicle_id, :content)
      end


    end
  end
end

app/controllers/api/v1/statuses_controller.rb
module Api
  module V1
    class StatusesController < ApplicationController

      def index
        respond_with Status.all
      end

      def create
        # i hate using vehicle like this as it cant be the StatusesControllers 
        # responiblity to deal with vehicles but i couldn't find another way to 
        # set up the associations properly when creating a status
        s = Status.update_for_vehicle_id(status_params[:vehicle_id], status_params, current_user)

        v = Vehicle.find(status_params[:vehicle_id])
        prev_status = v.status
        v.build_status(status_params)
        v.status.user = current_user
        prev_status.destroy #this is so I can query a User instance for it's statuses 
                            #and only get active statuses not every status they ever set
                            #avi suggested user has_many statuses, has_one current_status
        Note.note_for_status(v.status)


        if v.save
          render json: v.status
        end 
      end

      def destroy
        respond_with Status.destroy(params[:id])
      end


      private

      def status_params
        params.require(:status).permit(:user_id, :vehicle_id, :vehicle_status)
      end


    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController

      def index
        @users = User.all
        render json: @users
      end

      def show
        @user = User.find_by(name: params[:id])
        # this is so the route will display the name
        # for angular $resource to work it has to be passed as 'id'
        render json: @user
      end

    end
  end
end

app/controllers/api/v1/vehicles_controller.rb
module Api
  module V1
    class VehiclesController < ApplicationController

      def index
        @vehicles = Vehicle.all
        render json: @vehicles
      end

      def show
        @vehicle = Vehicle.find_by(id: params[:id])
        render json: @vehicle
      end

      def create
        if params[:vehicle]
          @vehicle = Vehicle.new(vehicle_params)
          @vehicle.build_status(user_id: 1, vehicle_status: 'Available')
        else
          @vehicle = Vehicle.new(angular_vehicle_params.except(:format))
          @vehicle.build_status(user_id: 1, vehicle_status: 'Available')
        end
        if @vehicle.save 
          render json: @vehicle
        end 
      end

      def update 
        @vehicle = Vehicle.find_by(id: params[:id])
        if @vehicle.update(angular_vehicle_params.except(:format))
          render json: @vehicle
        end 
      end


      private

      def vehicle_params
        params.require(:vehicle).permit(:stock_no, :year, :make, :model, :VIN, 
                                        :odometer, :msrp, :dealer_price, :color,
                                        :interior_color, :photo_url_list, :engine,
                                        :drive_train, :fuel, :body_type, :options,
                                        :transmission, :new_or_used, :storage, 
                                        :delivered, :invoice)
      end

      def angular_vehicle_params
        params.permit(:stock_no, :year, :make, :model, :VIN, 
                      :odometer, :msrp, :dealer_price, :color,
                      :interior_color, :photo_url_list, :engine,
                      :drive_train, :fuel, :body_type, :options,
                      :transmission, :new_or_used, :storage, 
                      :delivered, :invoice, :id, :format)
      end


    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  
  respond_to :json


  def angular
    render 'layouts/application'
  end
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  require 'csv'

  def index
    @vehicles = Vehicle.all
  end

  def upload
  end

  def import
    Vehicle.import(params[:file], params[:new_or_used])
    flash[:message] = "File Uploaded"
    redirect_to vehicles_upload_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/data/_vehiclecard.html.erb
<!-- add odometer and new/used status and short list of options -->
<div class='card_left'>
  <div class='card_header'>
    <h4><%= vehicle.year %> <%= vehicle.make %> <%= vehicle.model %></h4>
    <h5><%= vehicle.color %></h5>
  </div>
  <div class='car_picture'>
    i'm a picture<!-- last uploaded vehicle pic goes here or if there isn't one we need a place holder -->
  </div>
  <div>
    <p>MSRP: <%= vehicle.msrp %></p>
    <p>Stock Number: <%= vehicle.stock_no %></p>
    <p>Vin: <%= vehicle.VIN %></p>
  </div>
</div>

<div class='card_right'>
  <p>Status: Hold in F and I</p>
  <p>Status applied by: Tony S.</p>
</div>

app/views/data/index.html.erb
<div class='container-fluid'>

    <div class='row' id = 'first_row'>
        <div class='col-sm-1' id ='first_col'>I'm a search bar and small details can be listed below me. Such as: '50 results' or a link that jumps to that car like '2015 fiesta blue'</div>
        <div class='col-sm-11' id ='second_col'>I should have tabs because tabs are cool.</div>
    
    </div>

    <div class='row' id = 'second_row'>
        <div class='col-sm-1' id ='first_col'></div>
        <div class='col-sm-7' id ='second_col'>

            <div class='vehicle_card' id='test_drive' notes='will add to class based on status then i can get rid of the id here'>
                <%= render partial: 'vehiclecard', locals: { vehicle: @vehicles.first }%>
            </div>
            <div class='vehicle_card' id='sold' notes='will add to class based on status then i can get rid of the id here'>
                <%= render partial: 'vehiclecard', locals: { vehicle: @vehicles.last }%>
            </div>
            <div class='vehicle_card' id='sold' notes='will add to class based on status then i can get rid of the id here'>
                <%= render partial: 'vehiclecard', locals: { vehicle: @vehicles.first }%>
            </div>

            <% @vehicles.each do |vehicle| %>
                <div class='vehicle_card' id='FandI' notes='will add to class based on status then i can get rid of the id here'>
                    <%= render partial: 'vehiclecard', locals: { vehicle: vehicle }%>
                </div>
            <% end %>
 
         </div>

        <div class='col-sm-3' id ='third_col'>
<!--             I don't really want to iterate twice here but I can't figure out 
            how to put content in two seperate divs
            with one loop -->
            <% @vehicles.each do |vehicle| %>
                <div class='vehicle-options' id='first_vehicle'><p>Maybe a list of options goes here to?</p><a href='Car show page'>Click for Invoice and Details</a></div> 
            <% end %>

        </div>

        <div class= 'col-sm-1' id = 'fourth_col'>
        </div>

    </div>


<!-- <div class='row' id ='third_row'>
    <div class='col-sm-12'>one</div>
</div>  -->

</div>

app/views/data/testindex.html.erb
<div class='container-fluid'>

    <div class='row' id = 'first_row'>
        <div class='col-sm-1' id ='first_col'>I'm a search bar and small details can be listed below me. Such as: '50 results' or a link that jumps to that car like '2015 fiesta blue'</div>
        <div class='col-sm-11' id ='second_col'>I should have tabs because tabs are cool.</div>
    
    </div>

    <div class='row' id = 'second_row'>
        <div class='col-sm-1' id ='first_col'></div>
        <div class='col-sm-7' id ='second_col'>

            <div class='vehicle_card' id='test_drive' notes='will add to class based on status then i can get rid of the id here'>
                <%= render partial: 'vehiclecard', locals: { vehicle: @vehicles.first }%>
            </div>
            <div class='vehicle_card' id='sold' notes='will add to class based on status then i can get rid of the id here'>
                <%= render partial: 'vehiclecard', locals: { vehicle: @vehicles.last }%>
            </div>
            <div class='vehicle_card' id='sold' notes='will add to class based on status then i can get rid of the id here'>
                <%= render partial: 'vehiclecard', locals: { vehicle: @vehicles.first }%>
            </div>

            <% @vehicles.each do |vehicle| %>
                <div class='vehicle_card' id='FandI' notes='will add to class based on status then i can get rid of the id here'>
                    <%= render partial: 'vehiclecard', locals: { vehicle: vehicle }%>
                </div>
            <% end %>
 
         </div>

        <div class='col-sm-3' id ='third_col'>
<!--             I don't really want to iterate twice here but I can't figure out 
            how to put content in two seperate divs
            with one loop -->
            <% @vehicles.each do |vehicle| %>
                <div class='vehicle-options' id='first_vehicle'><p>Maybe a list of options goes here to?</p><a href='Car show page'>Click for Invoice and Details</a></div> 
            <% end %>

        </div>

        <div class= 'col-sm-1' id = 'fourth_col'>
        </div>

    </div>


<!-- <div class='row' id ='third_row'>
    <div class='col-sm-12'>one</div>
</div>  -->

</div>

app/views/data/upload.html.erb
Import Inventory:

<!-- I'd much rather make an API call to ford but they aren't playing nice -->

<%= form_tag vehicles_import_path, multipart: true do %>
  <%= file_field_tag :file %><br>
  <%= select_tag "new_or_used", "<option>New</option><option>Pre-Owned</option>".html_safe %><br>
  <%= submit_tag "Import CSV" %>
<% end %>

<br>
<br>

<div class = 'message'>
<%= flash[:message] if flash[:message] %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EZI</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body ng-app="app">

<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 5px;
    text-align: left;
}
</style>

<div ng-controller="SessionController as session">
  <div class='col-sm-2' id='leftsidebar'>
    <h2 id='logotype'><i>EZI</i></h2>
    <div ng-if="session.userrole === 'admin'" ng-include="'_admin_nav.html'"></div>
    <div ng-if="session.userrole === 'user'" ng-include="'_user_nav.html'"></div>

    <ul>
      <li ng-hide="session.signedIn()"><a href="#" ui-sref="welcome.signin">Log In</a></li>
      <li ng-hide="session.signedIn()"><a href="#" ui-sref="welcome.signup">Register</a></li>
      <li ng-show="session.signedIn()"><a href="#" ng-click="session.logout()">Log Out</a></li>
    </ul>

  </div>
  <div class='col-sm-10' style='float: right'>
    <ui-view></ui-view>
  </div>
</div>

<%= javascript_include_tag 'application' %>
</body>
</html>